/*
 * File: app/store/StTreeSprav.js
 * Date: Tue Aug 11 2020 20:25:16 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dobrobut.store.StTreeSprav', {
    extend: 'Ext.data.TreeStore',
    alias: 'store.stTreeSprav',

    requires: [
        'Dobrobut.model.MdTreeOrg',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stTreeSprav',
            model: 'Dobrobut.model.MdTreeOrg',
            root: {
                expanded: true,
                children: [
                    {
                        id: 'Subsidia',
                        text: 'Субсидии',
                        expanded: false,
                        children: [
                            {
                                id: 'tabSubsidia',
                                leaf: true,
                                text: 'Субсидия'
                            },
                            {
                                id: 'PrintSubsUtsznAll',
                                leaf: true,
                                text: 'Свод субсидий по ОСМД'
                            },
                            {
                                id: 'tabSubsUtszn',
                                leaf: true,
                                text: 'Сверка по Субсидиям'
                            },
                            {
                                id: 'tabHouseResidents',
                                leaf: true,
                                text: 'Справка для субсидий'
                            },
                            {
                                id: 'tabVozvratSubsidia',
                                leaf: true,
                                text: 'Возврат субсидий'
                            }
                        ]
                    },
                    {
                        id: 'Lgota',
                        text: 'Льготы',
                        expanded: false,
                        children: [
                            {
                                id: 'tabLgota',
                                leaf: true,
                                text: 'Справочник льгот'
                            },
                            {
                                id: 'tabLgotnik',
                                leaf: true,
                                text: 'Льготники'
                            },
                            {
                                id: 'tabSprUtszn',
                                leaf: true,
                                text: 'Справочник для УТиСЗН'
                            },
                            {
                                id: 'ItogBudjetPoGroupOsmdSv',
                                leaf: true,
                                text: 'Свод по группам по дому'
                            },
                            {
                                id: 'ItogBudjetPoGroupRazvOsmdSv',
                                leaf: true,
                                text: 'Разв по группам льгот'
                            },
                            {
                                id: 'PrintLgotaUtsznAll',
                                leaf: true,
                                text: 'Свод льгот по всем ОСМД'
                            },
                            {
                                id: 'tabLgotaUtszn',
                                leaf: true,
                                text: 'Сверка по Льготникам'
                            }
                        ]
                    },
                    {
                        id: 'Management',
                        text: 'Добробут',
                        expanded: false,
                        children: [
                            {
                                id: 'ItogMonthDobrobut',
                                leaf: true,
                                text: 'Итоговый по добробут'
                            },
                            {
                                id: 'ItogMonthHouse',
                                leaf: true,
                                text: 'Итоговый по дому'
                            },
                            {
                                id: 'DolgiDobrobut',
                                leaf: true,
                                text: 'Долги ОСМД'
                            },
                            {
                                id: 'SchetDobrobut',
                                leaf: true,
                                text: 'Уведомления'
                            },
                            {
                                id: 'tabKvartplata',
                                leaf: true,
                                text: 'Тариф и начисление'
                            },
                            {
                                id: 'ControlAllDobrobut',
                                leaf: true,
                                text: 'Контроль'
                            },
                            {
                                id: 'ControlDolgDobrobut',
                                leaf: true,
                                text: 'Контроль долг ОСМД'
                            },
                            {
                                id: 'NachislenoAllDobrobut',
                                leaf: true,
                                text: 'Начислено'
                            },
                            {
                                id: 'SvodHousesOsmd',
                                leaf: true,
                                text: 'Свод инфо по домам'
                            },
                            {
                                id: 'KassaDobrobut',
                                text: 'Касса',
                                expanded: false,
                                children: [
                                    {
                                        id: 'KassaAddressDobrobut',
                                        leaf: true,
                                        text: 'Реестр по адресам'
                                    },
                                    {
                                        id: 'KassaPrixodDobrobut',
                                        leaf: true,
                                        text: 'Реестр по кассе'
                                    },
                                    {
                                        id: 'KassaDateDobrobut',
                                        leaf: true,
                                        text: 'Реестр по дате'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        id: 'Osmd',
                        text: 'ОСББ',
                        expanded: false,
                        children: [
                            {
                                id: 'Budjet',
                                text: 'Бюджет',
                                expanded: false,
                                children: [
                                    {
                                        id: 'ItogBudjetPoGroupOsmd',
                                        leaf: true,
                                        text: 'Свод по группам льгот'
                                    },
                                    {
                                        id: 'ItogBudjetPoGroupRazvOsmd',
                                        leaf: true,
                                        text: 'Разв по группам льгот'
                                    }
                                ]
                            },
                            {
                                id: 'KassaOsmd',
                                text: 'Касса',
                                expanded: false,
                                children: [
                                    {
                                        id: 'KassaAddressOsmd',
                                        leaf: true,
                                        text: 'Реестр по адресам'
                                    },
                                    {
                                        id: 'KassaPrixodOsmd',
                                        leaf: true,
                                        text: 'Реестр по кассе'
                                    },
                                    {
                                        id: 'KassaDateOsmd',
                                        leaf: true,
                                        text: 'Реестр по дате'
                                    }
                                ]
                            },
                            {
                                id: 'AppHistory',
                                leaf: true,
                                text: 'Изменения по дому'
                            },
                            {
                                id: 'SchetOsmd',
                                leaf: true,
                                text: 'Уведомления'
                            },
                            {
                                id: 'InfoHouse',
                                leaf: true,
                                text: 'Характеристика дома'
                            },
                            {
                                id: 'ItogMonthOsmd',
                                leaf: true,
                                text: 'Итоговый за месяц'
                            },
                            {
                                id: 'NachislenoAllHouseOsmd',
                                leaf: true,
                                text: 'Начислено по дому'
                            },
                            {
                                id: 'DolgiOsmd',
                                leaf: true,
                                text: 'Должники'
                            },
                            {
                                id: 'ControlOsmd',
                                leaf: true,
                                text: 'Контроль'
                            }
                        ]
                    }
                ]
            },
            proxy: {
                type: 'ajax',
                url: 'local',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});