/*
 * File: app/model/MdRaion.js
 * Date: Sun May 24 2020 12:36:18 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dobrobut.model.MdRaion', {
    extend: 'Ext.data.Model',
    alias: 'model.mdRaion',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'raion_id'
        },
        {
            type: 'string',
            name: 'raion'
        }
    ]
});