/*
 * File: app/view/menu/TabPnCenter.js
 * Date: Sun May 24 2020 12:36:10 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dobrobut.view.menu.TabPnCenter', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpncenter',

    requires: [
        'Dobrobut.view.menu.TabPnCenterViewModel',
        'Dobrobut.view.sprav.TabLogin',
        'Dobrobut.view.flat.TabKassa',
        'Dobrobut.view.flat.TabAppBti',
        'Dobrobut.view.flat.TabNachApp',
        'Dobrobut.view.flat.TabAppVodomer',
        'Dobrobut.view.flat.TabAppTeplomer',
        'Dobrobut.view.flat.TabOplata',
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'tabpncenter'
    },
    border: false,
    id: 'tabPnCenter',
    activeTab: 0,

    items: [
        {
            xtype: 'tabLogin',
            title: 'My Tab'
        },
        {
            xtype: 'tabkassa'
        },
        {
            xtype: 'tabappbti'
        },
        {
            xtype: 'tabnachapp'
        },
        {
            xtype: 'tabAppVodomer'
        },
        {
            xtype: 'tabAppTeplomer'
        },
        {
            xtype: 'taboplata',
            title: 'Платежи'
        }
    ]

});